ALTER TABLE public."User"
  ADD COLUMN IF NOT EXISTS "emailVerifiedAt" timestamptz,
  ADD COLUMN IF NOT EXISTS "complimentaryAccess" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.app_abuse_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  subject_hash text NOT NULL,
  user_id text REFERENCES public."User"(id) ON DELETE SET NULL,
  detail text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS app_abuse_events_event_type_subject_hash_created_at_idx
  ON public.app_abuse_events(event_type, subject_hash, created_at);

CREATE TABLE IF NOT EXISTS public.secure_devices (
  id text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES public."User"(id) ON DELETE CASCADE,
  "deviceKey" text NOT NULL,
  name text NOT NULL DEFAULT '',
  os text NOT NULL DEFAULT '',
  "appVersion" text NOT NULL DEFAULT '',
  "lastLoginAt" timestamptz NOT NULL DEFAULT now(),
  "lastActiveAt" timestamptz NOT NULL DEFAULT now(),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  UNIQUE ("userId", "deviceKey")
);
CREATE INDEX IF NOT EXISTS secure_devices_userId_lastLoginAt_idx
  ON public.secure_devices("userId", "lastLoginAt");

CREATE TABLE IF NOT EXISTS public.app_sessions_secure (
  id text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES public."User"(id) ON DELETE CASCADE,
  "deviceId" text NOT NULL REFERENCES public.secure_devices(id) ON DELETE CASCADE,
  "tokenHash" text NOT NULL UNIQUE,
  "expiresAt" timestamptz NOT NULL,
  "lastSeenAt" timestamptz NOT NULL DEFAULT now(),
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS app_sessions_secure_userId_expiresAt_idx
  ON public.app_sessions_secure("userId", "expiresAt");

CREATE TABLE IF NOT EXISTS public.trial_device_claims (
  "deviceKey" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES public."User"(id) ON DELETE CASCADE,
  "claimedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS trial_device_claims_userId_idx
  ON public.trial_device_claims("userId");

CREATE TABLE IF NOT EXISTS public.app_oauth_attempts (
  state text PRIMARY KEY,
  code_verifier text NOT NULL,
  device_key text NOT NULL,
  device_name text NOT NULL DEFAULT '',
  os text NOT NULL DEFAULT '',
  app_version text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  user_id text REFERENCES public."User"(id) ON DELETE CASCADE,
  error text,
  expires_at timestamptz NOT NULL,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS app_oauth_attempts_expires_at_idx
  ON public.app_oauth_attempts(expires_at);

CREATE TABLE IF NOT EXISTS public.app_verification_codes_secure (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  code_hash text NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  expires_at timestamptz NOT NULL,
  sent_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id text REFERENCES public."User"(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS app_verification_codes_secure_email_created_at_idx
  ON public.app_verification_codes_secure(email, created_at);

CREATE TABLE IF NOT EXISTS public.app_payments (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES public."User"(id) ON DELETE CASCADE,
  method text NOT NULL,
  amount integer NOT NULL,
  base_amount integer NOT NULL,
  unique_suffix integer NOT NULL DEFAULT 0,
  amount_usd numeric(10,2),
  currency text NOT NULL DEFAULT 'IDR',
  status text NOT NULL DEFAULT 'pending',
  reference text NOT NULL DEFAULT '',
  gateway text NOT NULL DEFAULT 'manual',
  gateway_ref text,
  qr_string text,
  qr_url text,
  approve_url text,
  note text,
  verified_at timestamptz,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS app_payments_user_id_created_at_idx
  ON public.app_payments(user_id, created_at);

CREATE TABLE IF NOT EXISTS public.app_licenses (
  id text PRIMARY KEY,
  user_id text NOT NULL UNIQUE REFERENCES public."User"(id) ON DELETE CASCADE,
  code text NOT NULL,
  method text NOT NULL DEFAULT 'payment',
  payment_id text REFERENCES public.app_payments(id),
  activated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz
);

CREATE INDEX IF NOT EXISTS Download_userId_idx ON public."Download"("userId");
CREATE INDEX IF NOT EXISTS Session_userId_idx ON public."Session"("userId");
CREATE INDEX IF NOT EXISTS app_licenses_payment_id_idx ON public.app_licenses(payment_id);
CREATE UNIQUE INDEX IF NOT EXISTS app_licenses_payment_id_key
  ON public.app_licenses(payment_id) WHERE payment_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS app_licenses_code_key ON public.app_licenses(code);
CREATE INDEX IF NOT EXISTS job_targets_cv_id_idx ON public.job_targets(cv_id);
CREATE INDEX IF NOT EXISTS app_payments_gateway_gateway_ref_idx
  ON public.app_payments(gateway, gateway_ref);

DO $$
DECLARE
  table_name text;
BEGIN
  FOR table_name IN
    SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END
$$;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;

DO $$
BEGIN
  IF to_regprocedure('public.ordal_log_delete()') IS NOT NULL THEN
    ALTER FUNCTION public.ordal_log_delete() SET search_path = public, pg_temp;
  END IF;
  IF to_regprocedure('public.ordal_touch_updated_at()') IS NOT NULL THEN
    ALTER FUNCTION public.ordal_touch_updated_at() SET search_path = public, pg_temp;
  END IF;
END
$$;
